baseURL = "https://andoniabedul.github.io/"
languageCode = "en-us"
title = "Andoni Abedul"
description = "Tecnología, política, economía y pensamientos varios, en algunos casos inútiles, en otros quizás no tanto."
theme = "archie"

[author]
  name = "Andoni Abedul"
  homepage = "https://andoniabedul.github.io/"
  github = "andoniabedul"
  linkedin = "andoniabedul"
  twitter = "abedulfield"